import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/widgets/Footer/Footer";
import { ThemeProvider } from "@/shared/ui/theme-provider";
import { AppHeader } from "@/widgets/Header/app-header";
import { SmoothCursor } from "@/shared/ui/magicui/smooth-cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Гравитинод",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothCursor />
          <AppHeader />
          <main className="p-5">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
