import type { Metadata } from "next";
import "../globals.css";
import { Footer } from "@/widgets/ui/layouts/Footer/ui/Footer";
import { ThemeProvider } from "@/shared/ui/shadcn/theme-provider";
import { AppHeader } from "@/widgets/ui/layouts/Header/ui/app-header";
import { notFound } from 'next/navigation';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
// import { setRequestLocale } from 'next-intl/server';
// import { getMessages } from 'next-intl/server';
import { routing } from '@/i18n/routing';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [
    { locale: 'ru' },
    { locale: 'en' },
  ];
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {

  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} suppressHydrationWarning>

      <body className={`antialiased bg-[#0d102b]`}>
        <NextIntlClientProvider>
          {/* <NextIntlClientProvider  messages={messages}> */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppHeader />
            <main className="p-5">{children}</main>
            <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}